# 1.import all thr requiredpython libraries

In [11]:
import warnings
warnings.simplefilter('ignore')

In [12]:
import numpy as np
import pandas as pd

In [13]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [14]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [15]:

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# importing dataset

In [16]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [17]:
dataset=pd.read_excel('student_dataset.xlsx')

In [18]:
dataset

S.NO  ATTN  THEORY  Daily assn  TOTAL    certificate
0       1    20      38          25     83    DISTINCTION
1       2    15      25           0     40     COMPLETION
2       3    20      31          25     76    FIRST CLASS
3       4    20      25          25     70    FIRST CLASS
4       5    20      17          15     52    FIRST CLASS
..    ...   ...     ...         ...    ...            ...
362   363    15       0          10     25  PARTICIPATION
363   364    20       9          25     54     COMPLETION
364   365    15      20          25     60    FIRST CLASS
365   366    15       0          10     25  PARTICIPATION
366   367    20      23          10     53     COMPLETION

[367 rows x 6 columns]

In [19]:
dataset.shape

(367, 6)

In [20]:
dataset.head()

S.NO  ATTN  THEORY  Daily assn  TOTAL  certificate
0     1    20      38          25     83  DISTINCTION
1     2    15      25           0     40   COMPLETION
2     3    20      31          25     76  FIRST CLASS
3     4    20      25          25     70  FIRST CLASS
4     5    20      17          15     52  FIRST CLASS

In [21]:
dataset.tail()

S.NO  ATTN  THEORY  Daily assn  TOTAL    certificate
362   363    15       0          10     25  PARTICIPATION
363   364    20       9          25     54     COMPLETION
364   365    15      20          25     60    FIRST CLASS
365   366    15       0          10     25  PARTICIPATION
366   367    20      23          10     53     COMPLETION

# slice the dataset 

In [22]:
data=dataset.drop(['S.NO','TOTAL'],axis=1)
data

ATTN  THEORY  Daily assn    certificate
0      20      38          25    DISTINCTION
1      15      25           0     COMPLETION
2      20      31          25    FIRST CLASS
3      20      25          25    FIRST CLASS
4      20      17          15    FIRST CLASS
..    ...     ...         ...            ...
362    15       0          10  PARTICIPATION
363    20       9          25     COMPLETION
364    15      20          25    FIRST CLASS
365    15       0          10  PARTICIPATION
366    20      23          10     COMPLETION

[367 rows x 4 columns]

# unique values in dataset

In [23]:
data['certificate'].unique()

array(['DISTINCTION', 'COMPLETION', 'FIRST CLASS', 'PARTICIPATION'],
      dtype=object)

# grouping  the dataset 


In [24]:
data.groupby('certificate').size()

certificate
COMPLETION       117
DISTINCTION       32
FIRST CLASS       66
PARTICIPATION    152
dtype: int64

# encoding the data

In [25]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [26]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
data.iloc[:,3]=LabelEncoder().fit_transform(data.iloc[:,3])
data

ATTN  THEORY  Daily assn  certificate
0      20      38          25            1
1      15      25           0            0
2      20      31          25            2
3      20      25          25            2
4      20      17          15            2
..    ...     ...         ...          ...
362    15       0          10            3
363    20       9          25            0
364    15      20          25            2
365    15       0          10            3
366    20      23          10            0

[367 rows x 4 columns]

0-completion
1-distinction
2-first class
3-participation

In [29]:
x=data.iloc[:,:-1].values
x

array([[20, 38, 25],
       [15, 25,  0],
       [20, 31, 25],
       ...,
       [15, 20, 25],
       [15,  0, 10],
       [20, 23, 10]], dtype=int64)

In [30]:
y=data.iloc[:,3]
y

0      1
1      0
2      2
3      2
4      2
      ..
362    3
363    0
364    2
365    3
366    0
Name: certificate, Length: 367, dtype: int32

In [31]:
y=data.iloc[:,3].values
y

array([1, 0, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 2, 0, 3, 0, 0, 2, 0, 2, 1,
       2, 3, 1, 0, 3, 1, 2, 1, 0, 0, 0, 3, 2, 0, 0, 0, 1, 2, 1, 0, 1, 1,
       2, 0, 0, 0, 3, 0, 1, 2, 2, 2, 0, 3, 0, 2, 0, 1, 2, 2, 2, 1, 0, 3,
       1, 0, 3, 3, 0, 3, 1, 3, 0, 0, 3, 3, 3, 3, 1, 0, 2, 0, 3, 3, 0, 3,
       3, 2, 3, 3, 3, 2, 2, 0, 2, 0, 0, 1, 0, 1, 1, 2, 1, 2, 3, 1, 0, 3,
       3, 1, 3, 0, 3, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 3, 0, 1, 1, 0, 2, 0, 2, 0, 2, 0, 0,
       2, 0, 0, 3, 0, 0, 2, 0, 2, 2, 0, 3, 1, 3, 0, 2, 0, 1, 0, 0, 0, 2,
       2, 2, 0, 2, 2, 2, 0, 2, 2, 3, 0, 1, 3, 2, 3, 3, 1, 2, 1, 0, 3, 2,
       2, 2, 2, 3, 0, 0, 3, 3, 3, 0, 0, 0, 3, 3, 0, 3, 2, 0, 3, 3, 0, 3,
       3, 3, 0, 3, 0, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3,
       0, 0, 3, 0, 0, 3, 3, 2, 3, 3, 3, 0, 0, 3, 0,

# converting to dataframe  


# converting x to dataframe


In [32]:
x_frame=pd.DataFrame(x,columns=['attn','theory','Daily Assn'])
x_frame

attn  theory  Daily Assn
0      20      38          25
1      15      25           0
2      20      31          25
3      20      25          25
4      20      17          15
..    ...     ...         ...
362    15       0          10
363    20       9          25
364    15      20          25
365    15       0          10
366    20      23          10

[367 rows x 3 columns]

In [33]:
y_frame=pd.DataFrame(y)
y_frame

0
0    1
1    0
2    2
3    2
4    2
..  ..
362  3
363  0
364  2
365  3
366  0

[367 rows x 1 columns]

# divide the dataset into training set and testing set


# importing library for training and testing split set

In [34]:
from sklearn.model_selection import train_test_split 


In [35]:
x_train,x_test,y_train,y_test=train_test_split(x_frame,y_frame,test_size=0.2,random_state=0)


In [36]:
x_train

attn  theory  Daily Assn
63     25      36          25
241    25      21          25
306    15       0           0
317    20      21          10
245    15       0           0
..    ...     ...         ...
323    20       7          25
192    20       0          25
117    20      16           0
47     20      22          15
172    15       0           0

[293 rows x 3 columns]

In [37]:
from sklearn.neighbors import KNeighborsClassifier

# nearest neighbor implementation

In [38]:
knn=KNeighborsClassifier(n_neighbors=5)



# fitting the values in KNN

In [39]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

# prediction

In [40]:
y_predict=knn.predict(x_test)
y_predict

array([3, 2, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 0, 2, 0, 1, 0, 2, 1, 3, 3, 0,
       1, 0, 3, 3, 3, 0, 0, 2, 3, 2, 3, 3, 0, 0, 2, 3, 3, 0, 0, 3, 0, 3,
       0, 0, 0, 0, 3, 3, 3, 2, 0, 1, 3, 0, 0, 3, 2, 0, 2, 0, 1, 0, 3, 0,
       0, 3, 0, 3, 0, 3, 3, 0])

#  model evaluation & performance metrics


In [44]:
knn.score(x_train,y_train)




0.7849829351535836

In [45]:
knn.score(x_test,y_test)


0.6891891891891891

# importing neccesary metric 

In [42]:
from sklearn.metrics import confusion_matrix

# confusion matrix



In [43]:
con_matrix=confusion_matrix(y_test,y_predict)
con_matrix

array([[15,  0,  2,  1],
       [ 0,  3,  2,  0],
       [ 7,  2,  5,  0],
       [ 9,  0,  0, 28]], dtype=int64)

# hyper parameter optimization 
importing grid search module

