In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# numpy version check


In [2]:
import numpy as np

In [3]:
np.version.version

'1.25.2'

# one dimentional array 
we will be using numpy.array to create different dimentional arrays 
3.1 creating 1d array

1.syntax :numpy.array([values])

2.values:elements in the array


In [4]:
first_array =np.array([1,2,3,4,5])
print(first_array)

[1 2 3 4 5]


# two dimentional array 


# syntax:numpy.array([(values 1),(values 2)])

In [5]:
second_array=np.array([(1,2,3),(4,5,6)])

In [6]:
print(second_array)

[[1 2 3]
 [4 5 6]]


# three dimentional array

# array  of zeroes
syntax:numpy.zeros(shape,dtype=float,order='c')

In [7]:
zero_array =np.zeros((4,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# array of ones 


In [8]:
 
ones_array=np.ones((2,2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


# linspace
syntax:numpy.linspace(start,stop,num=50,endpoint=true,dtype=none,axis=0)

start:starting value of sequence

stop:end value of sequence

num=:number of samples to generate
 
endpoint=:in true stop at last sample ,otherwise its included default is true

dtype(optional):desired datatype of array

axis=(optional):axis along  which its stored



In [9]:
lin=np.linspace(0,10,50)
print(lin)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


# array manipulations
creating array

In [10]:
a=np.array([1,3,5])
print(a)

[1 3 5]


In [11]:
b=np.array([6,8,10])
print(b)

[ 6  8 10]


# transpose
#syntax:numpy.transpose(a,axes=none)


In [12]:
my_matrix=np.array([(11,22),(33,44)])
print(my_matrix)

[[11 22]
 [33 44]]


In [13]:
transpose=np.transpose(my_matrix)
print(transpose)

[[11 33]
 [22 44]]


# flattening array
we use ndarray.ravel for flattening operation
syntax:ndarray.ravel(order='c')
order:which order the flattening


In [14]:
transpose.ravel()

array([11, 33, 22, 44])

# reshaping the array 

syntax:ndarray.reshape(newshape)

In [15]:
first_array.reshape(5,1)
print(first_array)

[1 2 3 4 5]


In [16]:
a=np.array([1,2,3,4,])

In [17]:
print(a)

[1 2 3 4]


In [18]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

# array resize
##synax:ndarray.resize((new_size))

In [19]:
a.resize((2,2))

In [20]:
a

array([[1, 2],
       [3, 4]])

In [21]:
print(a)

[[1 2]
 [3 4]]
